[project]
name = "django-plus"
version = "0.1.0"
description = "An application that provides a set of tools and utilities to enhance the development experience with Django."
readme = "README.md"
requires-python = ">=3.14"
keywords = ["django", "python", "web development", "utilities", "tools"]
dependencies = [
    "boto3>=1.43.15",
    "django>=6.0.5",
    "django-environ>=0.13.0",
    "httpx>=0.28.1",
    "pyyaml>=6.0.3",
]
authors = [
  {name = "John Pendenque", email = "pendenquejohn@gmail.com"},
]
maintainers = [
  {name = "John Pendenque", email = "pendenquejohn@gmail.com"}
]
classifiers = [
  "Development Status :: 1 - Planning",
  "Operating System :: POSIX",
  "Operating System :: Unix",
  "Operating System :: Microsoft :: Windows",
  "Intended Audience :: Developers",
  "Topic :: Internet",
  "Topic :: Internet :: WWW/HTTP",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.14",
  "Natural Language :: English",
  "Operating System :: Microsoft :: Windows :: Windows 11",
  "Operating System :: MacOS"
]

[project.urls]
Homepage = "https://github.com/Zadigo/django_plus"
Documentation = "https://github.com/Zadigo/django_plus/wiki"
Repository = "https://github.com/Zadigo/django_plus.git"
Changelog = "https://github.com/Zadigo/django_plus/blob/main/CHANGELOG.md"

[dependency-groups]
dev = [
    "autopep8>=2.3.2",
    "coverage>=7.14.0",
    "django-browser-reload>=1.21.0",
    "django-debug-toolbar>=6.3.0",
    "django-watchfiles>=1.4.0",
    "factory-boy>=3.3.3",
    "pytest>=9.0.3",
    "pytest-aio>=2.1.7",
    "pytest-cov>=7.1.0",
    "pytest-django>=4.12.0",
    "pytest-env>=1.6.0",
    "pytest-playwright>=0.8.0",
    "pytest-timeout>=2.4.0",
]

[tool.pytest.ini_options]
addopts = [
    "--cov=django_plus",
    "--cov-report=html:cov_html",
    "--cov-report=term-missing"
]

[tool.pyright]
typeCheckingMode = "off"
reportMissingImports = true
reportUntypedBaseClass = true

[tool.pytest_env]
env_files = [".env", ".env.test"]

[tool.setuptools]
packages = ["django_plus"]

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true
