# Generated by Django 6.0.5 on 2026-07-31 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('book', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_of_birth', models.DateField(blank=True, help_text="The user's date of birth.", null=True)),
                ('home_phone', models.CharField(blank=True, help_text="The user's home phone number.", max_length=20, null=True)),
                ('mobile_phone', models.CharField(blank=True, help_text="The user's mobile phone number.", max_length=20, null=True)),
                ('business_phone', models.CharField(blank=True, help_text="The user's business phone number.", max_length=20, null=True)),
                ('company', models.CharField(blank=True, help_text='The company or organization the user is associated with.', max_length=255, null=True)),
                ('job_title', models.CharField(blank=True, help_text="The user's job title or position within the company.", max_length=255, null=True)),
                ('street_address', models.CharField(blank=True, help_text="The user's street address.", max_length=255, null=True)),
                ('city', models.CharField(blank=True, help_text='The city where the user resides.', max_length=100, null=True)),
                ('state', models.CharField(blank=True, help_text='The state or province where the user resides.', max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, help_text="The postal or ZIP code for the user's address.", max_length=20, null=True)),
                ('country', models.CharField(blank=True, help_text='The country where the user resides.', max_length=100, null=True)),
                ('website', models.URLField(blank=True, help_text="The user's personal or professional website.", null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or information about the user.', null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='TimestampedTestModel',
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='models_user_profile_user_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['street_address', 'city', 'state', 'postal_code', 'country'], name='models_user_profile_updated_on_idx'),
        ),
    ]
