# Generated by Django 6.0.5 on 2026-07-31 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_author_book_journal_userprofile_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userprofile',
            new_name='user_profile_user_idx',
            old_name='models_user_profile_user_idx',
        ),
        migrations.RenameIndex(
            model_name='userprofile',
            new_name='user_profile_updated_on_idx',
            old_name='models_user_profile_updated_on_idx',
        ),
    ]
