on:
  push:
    branches:
      - main

jobs:
  onubuntu-latest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.14
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'tests/requirements/py3.txt'
      - name: Install dependencies
        run: |
          pip install uv
          uv sync
      - name: Run tests
        run: |
          uv run pytest
